### ISSUE TITLE
Error in Installation 

### ISSUE THREAD

**Issue by lincolnn** [cloudbrain/cloudbrain#21] opened 2016-10-21 04:23 UTC
Ran sudo python setup.py develop --user..

Trace:
no previously-included directories found matching 'benchmarks/env'
no previously-included directories found matching 'benchmarks/results'
no previously-included directories found matching 'benchmarks/html'
no previously-included directories found matching 'benchmarks/scipy'
no previously-included directories found matching 'scipy/special/tests/data/boost'
no previously-included directories found matching 'scipy/special/tests/data/gsl'
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/source/generated'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution

**Comment by flysonic10** [comment] 2016-10-22 03:15
I'm able to reproduce the error on install.

So far it doesn't seem to affect publish mock data.

**Comment by marionleborgne** [comment] 2016-10-24 00:18
@flysonic10 @lincolnn. I am not able to reproduce. Questions:
1. Could you post the full stack trace?
2. What python distribution are you using? OSX system python or anaoconda?
3. What is the output of `python -c "import scipy; print(scipy.__version__)"`?

**Comment by flysonic10** [comment] 2016-10-25 05:24
I found the issue. scipy has a dependency on gfortran. Here's how to fix it:

Mac:
brew install gcc 

Linux:
sudo apt-get install libatlas-base-dev gfortran

I'll update the setup docs.

**Comment by flysonic10** [comment] 2016-10-25 05:27
Docs updated: https://github.com/cloudbrain/cloudbrain/wiki/1.-Setup

Closing.

**Closed by flysonic10** 2016-10-25 05:27 UTC
